### ISSUE TITLE
Failure running integration tests profile 

### ISSUE THREAD

**Issue by filfreire** [skapral/poetryclub#5]
When I attempt to run
```
mvn clean install -Pintegration_tests
```

All tests fail with this kind of error:
```
[ERROR] produceTests[4]  Time elapsed: 3.197 s  <<< ERROR!
java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
```

/cc @skapral

**Comment by skapral** [comment]
@filfreire I haven't yet provided the documentation on how to deploy and run the integration tests. For now, the tests expect an instance of [chromedriver](http://chromedriver.chromium.org/downloads), available at the PATH. Also, for running itests, you'll need Docker, installed on your host.

**Comment by skapral** [comment]
@filfreire the documentation on how to run integartion tests will be provided in scope of #4. As for this issue, I suggest to close it. Do you agree?

**Comment by filfreire** [comment]
@skapral agreed 👍
